# Generated by Django 6.0.5 on 2026-05-10 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('type_livraison', models.CharField(choices=[('retrait', 'Retrait à la boutique'), ('livraison', 'Livraison à domicile')], default='livraison', max_length=10)),
                ('wilaya', models.CharField(blank=True, choices=[('01', '01 - Adrar'), ('02', '02 - Chlef'), ('03', '03 - Laghouat'), ('04', '04 - Oum El Bouaghi'), ('05', '05 - Batna'), ('06', '06 - Béjaïa'), ('07', '07 - Biskra'), ('08', '08 - Béchar'), ('09', '09 - Blida'), ('10', '10 - Bouira'), ('11', '11 - Tamanrasset'), ('12', '12 - Tébessa'), ('13', '13 - Tlemcen'), ('14', '14 - Tiaret'), ('15', '15 - Tizi Ouzou'), ('16', '16 - Alger'), ('17', '17 - Djelfa'), ('18', '18 - Jijel'), ('19', '19 - Sétif'), ('20', '20 - Saïda'), ('21', '21 - Skikda'), ('22', '22 - Sidi Bel Abbès'), ('23', '23 - Annaba'), ('24', '24 - Guelma'), ('25', '25 - Constantine'), ('26', '26 - Médéa'), ('27', '27 - Mostaganem'), ('28', "28 - M'Sila"), ('29', '29 - Mascara'), ('30', '30 - Ouargla'), ('31', '31 - Oran'), ('32', '32 - El Bayadh'), ('33', '33 - Illizi'), ('34', '34 - Bordj Bou Arréridj'), ('35', '35 - Boumerdès'), ('36', '36 - El Tarf'), ('37', '37 - Tindouf'), ('38', '38 - Tissemsilt'), ('39', '39 - El Oued'), ('40', '40 - Khenchela'), ('41', '41 - Souk Ahras'), ('42', '42 - Tipaza'), ('43', '43 - Mila'), ('44', '44 - Aïn Defla'), ('45', '45 - Naâma'), ('46', '46 - Aïn Témouchent'), ('47', '47 - Ghardaïa'), ('48', '48 - Relizane'), ('49', '49 - Timimoun'), ('50', '50 - Bordj Badji Mokhtar'), ('51', '51 - Ouled Djellal'), ('52', '52 - Béni Abbès'), ('53', '53 - In Salah'), ('54', '54 - In Guezzam'), ('55', '55 - Touggourt'), ('56', '56 - Djanet'), ('57', "57 - El M'Ghair"), ('58', '58 - El Meniaa')], max_length=2)),
                ('commune', models.CharField(blank=True, max_length=100)),
                ('adresse', models.TextField(blank=True)),
                ('mode_paiement', models.CharField(choices=[('cod', 'Paiement à la livraison (COD)'), ('ccp', 'Virement CCP / BaridiMob')], default='cod', max_length=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('expediee', 'Expédiée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commandes.order')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.product')),
            ],
        ),
    ]
