# Generated by Django 6.0.5 on 2026-05-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_client',
            field=models.EmailField(blank=True, help_text='Pour recevoir la confirmation par email', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='preuve_paiement',
            field=models.ImageField(blank=True, null=True, upload_to='preuves/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de confirmation'), ('confirmee', 'Confirmée'), ('attente_paiement', 'En attente de paiement'), ('paiement_recu', 'Preuve de paiement reçue'), ('expediee', 'Expédiée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
    ]
