# Generated by Django 6.0.5 on 2026-05-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoutiqueSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_boutique', models.CharField(default='Ma Boutique', max_length=100)),
                ('couleur_principale', models.CharField(default='#0d6efd', max_length=7)),
            ],
            options={
                'verbose_name': 'Configuration Boutique',
                'verbose_name_plural': 'Configuration Boutique',
            },
        ),
    ]
