# Generated by Django 6.0.5 on 2026-05-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutiquesettings',
            name='description',
            field=models.TextField(blank=True, help_text="Message de bienvenue affiché sur la page d'accueil"),
        ),
    ]
